---
title: "Prinstats homework 1"
output: html_notebook
---
## Questions
Consider the paper of David Spiegelhalter (available on Ufora). In this paper
the author examines the age-specific risk of dying (with or from) Covid-19 in
the UK. Table 2 in the paper, gives for several age categories the numbers
of reported Covid-19 deaths, numbers of non-covid related deaths, population
sizes, among other numbers.


## 1. Question

Assign to each age interval a numerical value given by the midpoint (e.g. for 0-4, the midpoint is 
(0+4)/2 =2) and let $p_i$ denote the corresponding
population size in the UK.
Assume that the number of non-covid deaths $(Y^N )$ within an age class
with midpoint $a_i$ $(i = 1,\ldots , 11)$ can be described by a Poisson distribution with mean given by

$$
\text{E}(Y^N|\text{age}=a_i) = p_i\exp(\beta_0^N+\beta_1^Na_i)
$$

(the superscript refers to non-covid).
Also for the covid-related deaths $(Y^C)$ we assume a Poisson distribution
with

$$
\text{E}(Y^C|\text{age}=a_i) = p_i\exp(\beta_0^C+\gamma\beta_1^Na_i)
$$

*How do you interpret the $\gamma$ parameter?*

### Solution

Besides the first and the last age intervals, the difference between the mid point from one age group to the other is 10 years. 

* Lets take a unit increase  in age as 10 years.  Then 
$$
\beta_1^N = \log \text{E}(Y^N|\text{age} = a_i+1) - \log \text{E}(Y^N|\text{age} = a_i)
$$
and 
 $$
\gamma\beta_1^N = \log \text{E}(Y^C|\text{age} = a_i+1) - \log \text{E}(Y^C|\text{age} = a_i)
$$
* $\beta_1^N$ is the expected change in the number of non-covid-19 deaths per unit increase in age in the logarithmic scale
* $\gamma \beta_1^N$ is the expected change in the number of covid-19 deaths per unit increase in age in the logarithmic scale
    
* $\gamma = \gamma\beta_1^N/\beta_1^N$ is ratio of the expected change in the number of covid-19 deaths on the expected change in the number of non-covid 19 deaths for a unit increase in age in the logarithmic scale
* $\gamma>0$ implies for a unit increase in age the expected change in the number of  covid-19 deaths is greater than that of non-covid 19 deaths.  
* $\gamma<0$ implies for a unit increase in age, the expected change in the number of  covid-19 deaths is less than that of non-covid 19 deaths. 
* $\gamma = 0$ implies for a unit increase in age, the expected change in the number of  covid-19 deaths is equal to  that of non-covid 19 deaths.  Hence dying from covid 19 compared to dying from a non-covid 19 cause is independent of age.


## 2. Question

Given the models from the previous question, and assuming that all num-
bers of deaths (both covid and non-covid) are independently distributed.  Construct the log-likelihood function and make a graph of the log-likelihood as a function of the $\gamma$ parameter. You may use the following estimates for the other parameters:

$$
\beta_0^N = −12.06 ~~ \beta_0^C = −14.15 ~~ \beta_0^N = 0.09836
$$

### Solution 
We have been told that  $Y^N$ and $Y^C$ follow a Poisson distribution, recall that if a random variable $K$ follows a Poission distribution, it has the follow mass function  

$$
P_\lambda(K=k) = f(k|\lambda) = \frac{\lambda^{k}e^{-\lambda}}{k!}
$$
Let's say we have observed $n$ values from $n$ random variables $K_1,\ldots,K_n$ that are:

* all identically distributed (i.e. they all follow a Poisson distribution with parameter $\lambda_i$, well not exactly identical since their mean $\lambda$s are different) 
* independent, i.e, $P(K_1,\ldots,K_n) = \prod_i P(K_i)$

The likelihood is then defined as a function of $\mathbf \Lambda = (\lambda_1,\ldots,\lambda_n)$ given the data, i.e.,
$$
L(\mathbf \Lambda|K_1=k_1,\ldots,K_n=k_n) = \prod_i P_{\lambda_i}(K_i=k_i) = \prod_if(k_i|\lambda_i) = \prod_i\frac{\lambda_i^{k_i}e^{-\lambda_i}}{k_i!}
$$
The log likelihood which is simpler transformation to work with is given by 
$$
l(\Lambda|K_1=k_1,\ldots,K_n=k_n) = \log \prod_i P_{\lambda_i}(K_i=k_i)  = \sum_i\log\frac{\lambda_i^{k_i}e^{-\lambda_i}}{k_i!}
$$


$$
l(\Lambda|K_1=k_1,\ldots,K_n=k_n)  = \sum_i  \big(k_i \log\lambda_i - \lambda_i  - \log k_i!\big)
$$


$$
l(\Lambda|K_1=k_1,\ldots,K_n=k_n)  = \sum_i k_i \log\lambda_i - \sum_i \lambda_i  - \sum_i \log k_i!
$$

For the problem at hand we have $\lambda_i^N = \text{E}(Y^N|\text{age}=a_i)$ for non-covid 19 deads and $\lambda_i^C = \text{E}(Y^C|\text{age}=a_i)$ for covid 19 deads.
And our parameter of interest is  $\gamma$, it is then sufficient to only look at the covid 19 smaple. 

$$
l(\gamma|Y^C_1=y^C_1,\ldots,Y^C_n=y^C_n)  = \sum_i y^C_i (\beta_0^C+\gamma\beta_1^Na_i) - \sum_i p_ie^{(\beta_0^C+\gamma\beta_1^Na_i)} - \sum_i \log y^C_i!
$$

The maximum likelihood estimator of $\gamma$ is the value of $\gamma$ that maximises  $l(\gamma|K_1=k_1,\ldots,K_n=k_n)$. Note that any value that maximises the log likelihood  also maximises the likelihood  because the $\log$  function is monotone. 

To find $\gamma$ that maximises $l(.)$, all we need to do is to solve for $\gamma$ in the equation $l^\prime(\gamma) = 0$ 

Now 

$$
l^\prime(\gamma) = \sum_iy_i^C\beta_i^N - \sum_i p_i\beta_1^Na_ie^{(\beta_0^C+\gamma\beta_1^Na_i)}
$$
$$
\sum_iy_i^C\beta_i^N - \sum_i p_i\beta_1^Na_ie^{(\beta_0^C+\gamma\beta_1^Na_i)}  = 0
$$

$$
\sum_i p_i\beta_1^Na_ie^{(\beta_0^C+\gamma\beta_1^Na_i)}  = \sum_iy_i^C\beta_i^N 
$$